# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoter', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite', models.ManyToManyField(related_name='user_fav', to='login.User')),
                ('posted_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quote', to='login.User')),
            ],
        ),
    ]
