# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login_Register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('plan', models.CharField(max_length=1000)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_on_trip', to='Login_Register.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserAndTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_going', to='travel.Trip')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_going', to='Login_Register.User')),
            ],
        ),
    ]
